package com.yunqiic.dataapi.dao;

import com.yunqiic.dataapi.db.domain.PineAlarm;
import com.yunqiic.dataapi.db.domain.PineAlarmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PineAlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    long countByExample(PineAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    int deleteByExample(PineAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long pineAlarmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    int insert(PineAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    int insertSelective(PineAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    PineAlarm selectOneByExample(PineAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    PineAlarm selectOneByExampleSelective(@Param("example") PineAlarmExample example, @Param("selective") PineAlarm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    List<PineAlarm> selectByExampleSelective(@Param("example") PineAlarmExample example, @Param("selective") PineAlarm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    List<PineAlarm> selectByExample(PineAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    PineAlarm selectByPrimaryKeySelective(@Param("pineAlarmId") Long pineAlarmId, @Param("selective") PineAlarm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    PineAlarm selectByPrimaryKey(Long pineAlarmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PineAlarm record, @Param("example") PineAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PineAlarm record, @Param("example") PineAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PineAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pine_alarm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PineAlarm record);
}